language: node_js
node_js:
  - "8.1.3"
install: yarn && yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  fqdn: biffud.com
  local-dir: build
  email: robots@biffud.com
  committer-from-gh: true
  target-branch: gh-pages
  on:
    branch: master
