language: node_js
deploy:
  provider: pages
  skip-cleanup: true
  deploy-key: deploy_key.enc
  keep-history: true
  fqdn: biffud.com
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
